//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS_PRO_MAX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public string Fullname { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }

        public void Edit(string fullname , int id)
        {
            Fullname = fullname;
            Title = "ÚãáíÉ ÊÚÏíá";
            Details = "Êã ÊÚÏíá ÇáÕäİ Ğí ÇáÑŞã ÇáÊÚÑíİí " + id.ToString();
            Timestamp = DateTime.Now;
        }
        public void delete(string fullname, int id)
        {
            Fullname = fullname;
            Title = "ÚãáíÉ ÍĞİ";
            Details = "Êã ÍĞİ ÇáÕäİ Ğí ÇáÑŞã ÇáÊÚÑíİí " + id.ToString();
            Timestamp = DateTime.Now;
        }
    }
}
